<a href="https://colab.research.google.com/github/natanhp/Breast-Cancer-Data-Preparation/blob/master/DataPreparationAssignmentipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

In [45]:
raw_data = pd.read_csv("Breast_cancer_data.csv")
raw_data.head()

mean_radius  mean_texture  ...  mean_smoothness  diagnosis
0        17.99         10.38  ...          0.11840          0
1        20.57         17.77  ...          0.08474          0
2        19.69         21.25  ...          0.10960          0
3        11.42         20.38  ...          0.14250          0
4        20.29         14.34  ...          0.10030          0

[5 rows x 6 columns]

In [20]:
raw_data.describe()

mean_radius  mean_texture  ...  mean_smoothness   diagnosis
count   569.000000    569.000000  ...       569.000000  569.000000
mean     14.127292     19.289649  ...         0.096360    0.627417
std       3.524049      4.301036  ...         0.014064    0.483918
min       6.981000      9.710000  ...         0.052630    0.000000
25%      11.700000     16.170000  ...         0.086370    0.000000
50%      13.370000     18.840000  ...         0.095870    1.000000
75%      15.780000     21.800000  ...         0.105300    1.000000
max      28.110000     39.280000  ...         0.163400    1.000000

[8 rows x 6 columns]

Check for empty value

In [10]:
raw_data.isnull().sum()

mean_radius        0
mean_texture       0
mean_perimeter     0
mean_area          0
mean_smoothness    0
diagnosis          0
dtype: int64

In [46]:
data_label = raw_data.pop("diagnosis")
data_label.shape
raw_data.shape

(569, 5)

In [50]:
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(raw_data)
print(scaled_data)

[[0.52103744 0.0226581  0.54598853 0.36373277 0.59375282]
 [0.64314449 0.27257355 0.61578329 0.50159067 0.28987993]
 [0.60149557 0.3902604  0.59574321 0.44941676 0.51430893]
 ...
 [0.45525108 0.62123774 0.44578813 0.30311771 0.28816467]
 [0.64456434 0.66351031 0.66553797 0.4757158  0.58833619]
 [0.03686876 0.50152181 0.02853984 0.01590668 0.        ]]
